pipeline {

agent any

environment {
    SCANNER_HOME = tool 'sonar-scanner'
}

stages {

    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('SonarQube Analysis') {
        steps {
            withSonarQubeEnv('SonarQube') {
                sh '''
                ${SCANNER_HOME}/bin/sonar-scanner \
                -Dsonar.projectKey=keyshell-payment \
                -Dsonar.projectName=keyshell-payment \
                -Dsonar.sources=. \
                -Dsonar.sourceEncoding=UTF-8
                '''
            }
        }
    }

    stage('Build Backend') {
        steps {
            dir('backend') {
                sh 'docker build -t keyshell-backend:v1 .'
            }
        }
    }

    stage('Build Frontend') {
        steps {
            dir('frontend/angular-ui') {
                sh 'docker build -t keyshell-frontend:v1 .'
            }
        }
    }

    stage('Verify Images') {
        steps {
            sh 'docker images | grep keyshell'
        }
    }
}

}
